const fs = require('fs');
let content = fs.readFileSync('js/u_init.js', 'utf8');

// I need to add import for object constants since the generated trobj uses them
const objectImports = `
import {
    BULLWHIP, WEAPON_CLASS, LEATHER_JACKET, ARMOR_CLASS, FEDORA, FOOD_RATION, FOOD_CLASS,
    PICK_AXE, TOOL_CLASS, TINNING_KIT, TOUCHSTONE, GEM_CLASS, SACK, TWO_HANDED_SWORD, AXE,
    RING_MAIL, BATTLE_AXE, SHORT_SWORD, CLUB, SLING, FLINT, ROCK, LEATHER_ARMOR, SCALPEL,
    LEATHER_GLOVES, STETHOSCOPE, POT_HEALING, POTION_CLASS, POT_EXTRA_HEALING, WAN_SLEEP,
    WAND_CLASS, SPE_HEALING, SPBOOK_CLASS, SPE_EXTRA_HEALING, SPE_STONE_TO_FLESH, APPLE,
    LONG_SWORD, LANCE, HELMET, SMALL_SHIELD, CARROT, ROBE, POT_WATER, CLOVE_OF_GARLIC,
    SPRIG_OF_WOLFSBANE, DAGGER, BOW, ARROW, CLOAK_OF_DISPLACEMENT, CRAM_RATION, POT_SICKNESS,
    LOCK_PICK, KATANA, YUMI, YA, SPLINT_MAIL, DART, SCR_MAGIC_MAPPING, SCROLL_CLASS,
    HAWAIIAN_SHIRT, EXPENSIVE_CAMERA, CREDIT_CARD, SPEAR, QUARTERSTAFF, CLOAK_OF_MAGIC_RESISTANCE,
    RING_CLASS, SPE_FORCE_BOLT, MAGIC_MARKER, SPE_PROTECTION, SPE_CONFUSE_MONSTER, TIN_OPENER,
    OIL_LAMP, BLINDFOLD, LEASH, TOWEL, WAN_WISHING, SHURIKEN
} from './objects.js';

// Also UNDEF_TYP is 0
const UNDEF_TYP = 0;
`;

content = content.replace("import { newhp, newpw, adjabil } from './exper.js';", "import { newhp, newpw, adjabil } from './exper.js';\n" + objectImports);
fs.writeFileSync('js/u_init.js', content);
